module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    type: "numeric",
    required: true,
    default: 237,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    type: "numeric",
    required: true,
    default: "0000",
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    type: "numeric",
    required: true,
    default: 3,
  },
  {
    field: "num_seq_registro_lote",
    startPos: 9,
    endPos: 13,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "cod_seg_registro_lote",
    startPos: 14,
    endPos: 14,
    length: 1,
    required: true,
    type: "alphanumeric",
    default: "B",
  },
  {
    field: "forma_iniciacao", //* OBRIGATÓRIO NO PIX
    startPos: 15,
    endPos: 17,
    length: 3,
    required: true,
    type: "alphanumeric",
    default: new Array(3).fill(" ").join(""),
  },
  {
    field: "favorecido_tipo_insc",
    startPos: 18,
    endPos: 18,
    length: 1,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "num_inscricao",
    startPos: 19,
    endPos: 32,
    length: 14,
    type: "numeric",
    required: true,
  },
  {
    field: "logradouro",
    startPos: 33,
    endPos: 62,
    length: 30,
    required: false,
    type: "alphanumeric", //* CAMPO NOVO
  },
  {
    field: "numero",
    startPos: 63,
    endPos: 67,
    length: 5,
    required: false,
    type: "numeric", //* CAMPO NOVO
  },
  {
    field: "complemento",
    startPos: 68,
    endPos: 82,
    length: 15,
    required: false,
    type: "alphanumeric", //* CAMPO NOVO
  },
  {
    field: "bairro",
    startPos: 83,
    endPos: 97,
    length: 15,
    required: false,
    type: "alphanumeric", //* CAMPO NOVO
  },
  {
    field: "cidade",
    startPos: 98,
    endPos: 117,
    length: 20,
    required: false,
    type: "alphanumeric", //* CAMPO NOVO
  },
  {
    field: "cep",
    startPos: 118,
    endPos: 125,
    length: 8,
    required: false,
    type: "numeric", //* CAMPO NOVO
  },
  {
    field: "uf",
    startPos: 126,
    endPos: 127,
    length: 2,
    required: false,
    type: "alphanumeric", //* CAMPO NOVO
  },
  {
    field: "data_vencimento",
    startPos: 128,
    endPos: 135,
    length: 8,
    required: true,
    type: "date",
  },
  {
    field: "valor_pagamento",
    startPos: 136,
    endPos: 150,
    length: 15,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "valor_pagamento", //& valor_abatimento
    startPos: 151,
    endPos: 165,
    length: 15,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "valor_desconto",
    startPos: 166,
    endPos: 180,
    length: 15,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(15).fill(0).join(""),
  },
  {
    field: "valor_mora",
    startPos: 181,
    endPos: 195,
    length: 15,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(15).fill(0).join(""),
  },
  {
    field: "valor_multa",
    startPos: 196,
    endPos: 210,
    length: 15,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(15).fill(0).join(""),
  },
  {
    field: "doc_favorecido",
    startPos: 211,
    endPos: 225,
    length: 15,
    required: false,
    type: "alphanumeric",
    default: new Array(15).fill(" ").join(""),
  },
  {
    field: "aviso",
    startPos: 226,
    endPos: 226,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: "0",
  },
  {
    field: "brancos",
    startPos: 227,
    endPos: 240,
    length: 14,
    type: "numeric",
    default: new Array(14).fill(0).join(""),
  },
];
