module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    required: true,
    default: 237,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    type: "numeric",
    required: true,
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    required: true,
    default: 3,
  },
  {
    field: "num_registro_lote",
    startPos: 9,
    endPos: 13,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "cod_seg_registro_lote",
    startPos: 14,
    endPos: 14,
    length: 1,
    required: true,
    default: "J",
    type: "alphanumeric",
  },
  {
    field: "brancos",
    startPos: 15,
    endPos: 15,
    length: 1,
    required: true,
    default: " ",
  },
  {
    field: "movimento_tipo",
    startPos: 16,
    endPos: 17,
    length: 2,
    required: true,
    type: "numeric",
    default: "00", //* É ESSE CÓDIGO?
  },
  {
    field: "codigo_registro",
    startPos: 18,
    endPos: 19,
    length: 2,
    required: true,
    type: "numeric",
    default: 52,
  },
  //* Sacado é quem paga
  {
    field: "inscricao_sacado",
    startPos: 20,
    endPos: 20,
    length: 1,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "num_inscricao_sacado",
    startPos: 21,
    endPos: 35,
    length: 15,
    type: "numeric",
    required: true,
  },
  {
    field: "nome_sacado",
    startPos: 36,
    endPos: 75,
    length: 40,
    required: true,
    type: "alphanumeric",
  },
  //* Cedente é quem recebe (fornecedor)
  {
    field: "inscricao_cedente",
    startPos: 76,
    endPos: 76,
    length: 1,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "num_inscricao_cedente",
    startPos: 77,
    endPos: 91,
    length: 15,
    type: "numeric",
    required: true,
  },
  {
    field: "nome_cedente",
    startPos: 92,
    endPos: 131,
    length: 40,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "inscricao_sacador",
    startPos: 132,
    endPos: 132,
    length: 1,
    required: true,
    type: "numeric",
    default: 0,
  },
  {
    field: "num_inscricao_sacador",
    startPos: 133,
    endPos: 147,
    length: 15,
    type: "numeric",
    required: true,
    default: new Array(15).fill(0).join(""),
  },
  {
    field: "nome_sacador",
    startPos: 148,
    endPos: 187,
    length: 40,
    type: "alphanumeric",
    required: true,
    default: new Array(40).fill(" ").join(""),
  },
  {
    field: "brancos",
    startPos: 188,
    endPos: 240,
    length: 53,
    type: "alphanumeric",
    default: new Array(53).fill(" ").join(""),
  },
];
