module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    required: true,
    default: 237,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    required: true,
    type: "numeric",
    default: new Array(4).fill(0).join(""),
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    required: true,
    default: 3,
  },
  {
    field: "num_registro_lote",
    startPos: 9,
    endPos: 13,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "cod_seg_registro_lote",
    startPos: 14,
    endPos: 14,
    length: 1,
    required: true,
    default: "O",
    type: "alphanumeric",
  },
  {
    field: "movimento_tipo",
    startPos: 15,
    endPos: 17,
    length: 3,
    required: true,
    type: "numeric",
    default: new Array(3).fill(0).join(""),
  },
  {
    field: "tributo",
    startPos: 18,
    endPos: 19,
    length: 2,
    required: true,
    type: "numeric",
    default: "02",
  },
  {
    field: "receita",
    startPos: 20,
    endPos: 23,
    length: 4,
    required: true,
    type: "numeric",
  },
  {
    field: "empresa_inscricao",
    startPos: 24,
    endPos: 24,
    length: 1,
    required: true,
    type: "number",
    default: 2,
  },
  {
    field: "cnpj_contribuinte",
    startPos: 25,
    endPos: 38,
    length: 14,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "periodo",
    startPos: 39,
    endPos: 46,
    length: 8,
    required: true,
    type: "date",
  },
  {
    field: "referencia",
    startPos: 47,
    endPos: 63,
    length: 17,
    required: true,
    type: "numeric",
  },
  {
    field: "valor_principal",
    startPos: 64,
    endPos: 77,
    length: 14,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "valor_principal",
    startPos: 78,
    endPos: 91,
    length: 14,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(14).fill(0).join(""),
  },
  {
    field: "juros",
    startPos: 92,
    endPos: 105,
    length: 14,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(14).fill(0).join(""),
  },
  {
    field: "valor_pagamento", // Esse é o valor pago
    startPos: 106,
    endPos: 119,
    length: 14,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "vencimento",
    startPos: 120,
    endPos: 127,
    length: 8,
    required: true,
    type: "date",
  },
  {
    field: "pagamento",
    startPos: 128,
    endPos: 135,
    length: 8,
    required: true,
    type: "date",
  },
  {
    field: "brancos",
    startPos: 136,
    endPos: 165,
    length: 30,
    required: false,
    default: new Array(30).fill(" ").join(""),
  },
  {
    field: "nome_contribuinte",
    startPos: 166,
    endPos: 195,
    length: 30,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "brancos",
    startPos: 196,
    endPos: 215,
    length: 20,
    required: false,
    default: new Array(21).fill(" ").join(""),
  },
  {
    field: "nosso_numero",
    startPos: 216,
    endPos: 230,
    length: 15,
    required: false,
    default: new Array(15).fill(" ").join(""),
  },
  {
    field: "codigos_ocorrencias",
    startPos: 231,
    endPos: 240,
    length: 10,
    required: false,
    default: new Array(10).fill(" ").join(""),
  },
];
