module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    required: true,
    default: 237,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    required: true,
    type: "numeric",
    default: new Array(4).fill(0).join(""),
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    required: true,
    default: 3,
  },
  {
    field: "num_registro_lote",
    startPos: 9,
    endPos: 13,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "cod_seg_registro_lote",
    startPos: 14,
    endPos: 14,
    length: 1,
    required: true,
    default: "O",
    type: "alphanumeric",
  },
  {
    field: "movimento_tipo",
    startPos: 15,
    endPos: 17,
    length: 3,
    required: true,
    type: "numeric",
    default: new Array(3).fill(0).join(""),
  },
  {
    field: "cod_barras",
    startPos: 18,
    endPos: 61,
    length: 44,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "nome_concessionaria",
    startPos: 62,
    endPos: 91,
    length: 30,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "data_vencimento",
    startPos: 92,
    endPos: 99,
    length: 8,
    required: true,
    type: "date",
  },
  {
    field: "data_pagamento",
    startPos: 100,
    endPos: 107,
    length: 8,
    required: false,
    type: "date",
    default: new Array(8).fill(" ").join(""),
  },
  {
    field: "valor_pagamento",
    startPos: 108,
    endPos: 122,
    length: 15,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "id_vencimento", //* doc_empresa
    startPos: 123,
    endPos: 142,
    length: 20,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "nosso_numero",
    startPos: 143,
    endPos: 162,
    length: 20,
    required: false,
    default: new Array(20).fill(" ").join(""),
  },
  {
    field: "brancos",
    startPos: 163,
    endPos: 230,
    length: 68,
    required: false,
    default: new Array(68).fill(" ").join(""),
  },
  {
    field: "ocorrencias",
    startPos: 231,
    endPos: 240,
    length: 10,
    required: false,
    default: new Array(10).fill(" ").join(""),
  },
];
