module.exports = [
  {
    field: "registro",
    startPos: 1,
    endPos: 1,
    length: 1,
    required: true,
    type: "numeric",
    default: 0,
  },
  {
    field: "operacao",
    startPos: 2,
    endPos: 2,
    length: 1,
    required: true,
    type: "numeric",
    default: 1,
  },
  {
    field: "literal_remessa",
    startPos: 3,
    endPos: 9,
    length: 7,
    required: true,
    type: "alphanumeric",
    default: "REMESSA",
  },
  {
    field: "cod_servico",
    startPos: 10,
    endPos: 11,
    length: 2,
    required: false,
    default: "01",
  },
  {
    field: "literal_servico",
    startPos: 12,
    endPos: 26,
    length: 15,
    required: true,
    type: "alphanumeric",
    default: "COBRANCA",
  },
  {
    field: "agencia",
    startPos: 27,
    endPos: 30,
    length: 4,
    required: true,
    type: "numeric",
  },
  {
    field: "zeros",
    startPos: 31,
    endPos: 32,
    length: 2,
    required: true,
    type: "numeric",
    default: new Array(2).fill(0).join(""),
  },
  {
    field: "conta",
    startPos: 33,
    endPos: 37,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "dac",
    startPos: 38,
    endPos: 38,
    length: 1,
    required: true,
    type: "numeric",
    default: new Array(1).fill(0).join(""),
  },
  {
    field: "brancos",
    startPos: 39,
    endPos: 46,
    length: 8,
    required: true,
    type: "alphanumeric",
    default: new Array(2).fill(0).join(""),
  },
  {
    field: "empresa_nome",
    startPos: 47,
    endPos: 76,
    length: 30,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "banco",
    startPos: 77,
    endPos: 79,
    length: 3,
    required: true,
    type: "alphanumeric",
    default: 341,
  },
  {
    field: "nome_banco",
    startPos: 80,
    endPos: 94,
    length: 15,
    required: true,
    type: "alphanumeric",
    default: "BANCO ITAU SA",
  },
  {
    field: "data_emissao", //* Data emissão
    startPos: 95,
    endPos: 100,
    length: 6,
    required: true,
    type: "date",
  },
  {
    field: "brancos",
    startPos: 101,
    endPos: 394,
    length: 294,
    required: false,
    type: "alphanumeric",
    default: new Array(294).fill(" ").join(""),
  },
  {
    field: "num_sequencial",
    startPos: 395,
    endPos: 400,
    length: 6,
    required: true,
    type: "numeric",
  },
];
