module.exports = [
    {
        field: 'banco',
        startPos: 1,
        endPos: 3,
        length: 3,
        required: true,
        default: 237
    },
    {
        field: "lote",
        startPos: 4,
        endPos: 7,
        length: 4,
        required: true,
        type: "numeric",
        default: new Array(4).fill(0).join(""),
      },
      {
        field: "registro",
        startPos: 8,
        endPos: 8,
        length: 1,
        required: true,
        type: "numeric",
        default: 3,
      },
      {
        field: "num_registro_lote",
        startPos: 9,
        endPos: 13,
        length: 5,
        required: true,
        type: "numeric",
        default: 1,
      },
      {
        field: "cod_seg_registro_lote",
        startPos: 14,
        endPos: 14,
        length: 1,
        required: true,
        type: "alphanumeric",
        default: "G",
      },
      {
        field: "brancos",
        startPos: 15,
        endPos: 15,
        length: 1,
        required: false,
        type: "alphanumeric",
        default: new Array(1).fill(" ").join(""),
      },
      {
        field: "cod_movimento",
        startPos: 16,
        endPos: 17,
        length: 2,
        required: true,
        type: "numeric",
        default: "01",
      },
      {
        field: "cod_barras",
        startPos: 18,
        endPos: 61,
        length: 44,
        required: true,
        type: "alphanumeric",
      },
      {
        field: "tipo_inscricao_cedente",
        startPos: 62,
        endPos: 62,
        length: 1,
        required: true,
        type: "numeric",
        default: 2,
      },
      {
        field: "inscricao_cedente",
        startPos: 63,
        endPos: 77,
        length: 15,
        required: true,
        type: "alphanumeric",
      },
      {
        field: "nome_cedente",
        startPos: 78,
        endPos: 107,
        length: 30,
        required: true,
        type: "alphanumeric",
      },
      {
        field: "data_vencimento",
        startPos: 108,
        endPos: 115,
        length: 8,
        required: true,
        type: "date",
      },
      {
        field: "valor",
        startPos: 116,
        endPos: 130,
        length: 15,
        required: true,
        type: "numeric",
      },
      {
        field: "qtde_moeda",
        startPos: 131,
        endPos: 145,
        length: 15,
        required: true,
        type: "numeric",
      },
      {
        field: "codigo_moeda",
        startPos: 146,
        endPos: 147,
        length: 2,
        type: "numeric",
        default: '09',
      },
      {
        field: "num_doc_cobranca",
        startPos: 148,
        endPos: 162,
        length: 15,
        type: "alphanumeric",
        default: new Array(10).fill(' ').join(""),
      },
      {
        field: "agencia",
        startPos: 163,
        endPos: 167,
        length: 5,
        type: "numeric",
        default: new Array(5).fill(0).join(""),
      },
      {
        field: "dac",
        startPos: 168,
        endPos: 168,
        length: 1,
        type: "numeric",
        default: new Array(1).fill(0).join(""),
      },
      {
        field: "praca_cobradora",
        startPos: 169,
        endPos: 178,
        length: 10,
        type: "alphanumeric",
        default: new Array(10).fill(' ').join(""),
      },
      {
        field: "carteira",
        startPos: 179,
        endPos: 179,
        length: 1,
        type: "numeric",
        default: 1,
      },
      {
        field: "especie_titulo",
        startPos: 180,
        endPos: 181,
        length: 2,
        type: "numeric",
        default: '99',
      },
      {
        field: "data_emissao",
        startPos: 182,
        endPos: 189,
        length: 8,
        required: true,
        type: "date",
      },
      {
        field: "juros",
        startPos: 190,
        endPos: 204,
        length: 15,
        type: "numeric",
        default: new Array(15).fill(0).join(""),
      },
      {
        field: "cod_desconto",
        startPos: 205,
        endPos: 205,
        length: 1,
        type: "numeric",
        default: 0,
      },
      {
        field: "data_desconto",
        startPos: 206,
        endPos: 213,
        length: 8,
        type: "date",
        default: new Array(8).fill(0).join(""),
      },
      {
        field: "valor_desconto",
        startPos: 214,
        endPos: 228,
        length: 15,
        type: "numeric",
        default: new Array(15).fill(0).join(""),
      },
      {
        field: "codigo_protesto",
        startPos: 229,
        endPos: 229,
        length: 1,
        type: "numeric",
        default: '3',
      },
      {
        field: "prazo_protesto",
        startPos: 230,
        endPos: 231,
        length: 2,
        type: "numeric",
        default: '00',
      },
      {
        field: "data_limite",
        startPos: 232,
        endPos: 239,
        length: 8,
        type: "date",
        default: new Array(8).fill(0).join(""),
      },
      {
        field: "cod_juros",
        startPos: 240,
        endPos: 240,
        length: 1,
        type: "numeric",
        default: '5',
      },
];

