module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    required: true,
    default: 341,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    required: true,
    type: "numeric",
    default: new Array(4).fill(0).join(""),
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    required: true,
    default: 3,
  },
  {
    field: "num_registro_lote",
    startPos: 9,
    endPos: 13,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "cod_seg_registro_lote",
    startPos: 14,
    endPos: 14,
    length: 1,
    required: true,
    default: "O",
    type: "alphanumeric",
  },
  {
    field: "movimento_tipo",
    startPos: 15,
    endPos: 17,
    length: 3,
    required: true,
    type: "numeric",
    default: new Array(3).fill(0).join(""),
  },
  {
    field: "cod_barras",
    startPos: 18,
    endPos: 65,
    length: 48,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "nome_concessionaria",
    startPos: 66,
    endPos: 95,
    length: 30,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "data_vencimento",
    startPos: 96,
    endPos: 103,
    length: 8,
    required: true,
    type: "date",
  },
  {
    field: "moeda",
    startPos: 104,
    endPos: 106,
    length: 3,
    required: false,
    type: "alphanumeric",
    default: "REA",
  },
  {
    field: "quantidade_moeda",
    startPos: 107,
    endPos: 121,
    length: 15,
    required: false,
    type: "numeric",
    default: new Array(15).fill(0).join(""),
  },
  {
    field: "valor_pagamento",
    startPos: 122,
    endPos: 136,
    length: 15,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "data_pagamento",
    startPos: 137,
    endPos: 144,
    length: 8,
    required: true,
    type: "date",
  },

  {
    field: "valor_pagamento", // Esse é o valor pago
    startPos: 145,
    endPos: 159,
    length: 15,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "brancos",
    startPos: 160,
    endPos: 162,
    length: 3,
    required: false,
    default: new Array(3).fill(" ").join(""),
  },
  {
    field: "nota_fiscal",
    startPos: 163,
    endPos: 171,
    length: 9,
    required: false,
    type: "numeric",
    default: new Array(9).fill(0).join(""),
  },
  {
    field: "brancos",
    startPos: 172,
    endPos: 174,
    length: 3,
    required: false,
    default: new Array(3).fill(" ").join(""),
  },
  {
    field: "id_vencimento",
    startPos: 175,
    endPos: 194,
    length: 20,
    required: false,
    default: "CC",
  },
  {
    field: "brancos",
    startPos: 195,
    endPos: 215,
    length: 21,
    required: false,
    default: new Array(21).fill(" ").join(""),
  },
  {
    field: "nosso_numero",
    startPos: 216,
    endPos: 230,
    length: 15,
    required: false,
    default: new Array(15).fill(" ").join(""),
  },
  {
    field: "ocorrencias",
    startPos: 231,
    endPos: 240,
    length: 10,
    required: false,
    default: new Array(10).fill(" ").join(""),
  },
];
