module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    required: true,
    default: 237,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    required: true,
    type: "numeric",
    default: "0000",
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    required: true,
    default: "0",
  },
  {
    field: "brancos",
    startPos: 9,
    endPos: 17,
    length: 9,
    required: false,
    default: new Array(9).fill(" ").join(""),
  },
  {
    field: "empresa_tipo_insc",
    startPos: 18,
    endPos: 18,
    length: 1,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "cnpj_empresa",
    startPos: 19,
    endPos: 32,
    length: 14,
    required: true,
    type: "numeric",
  },
  {
    field: "cod_convenio",
    startPos: 33,
    endPos: 52,
    length: 20,
    required: true,
    default: 543568,
  },
  {
    field: "agencia",
    startPos: 53,
    endPos: 57,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "dv_agencia",
    startPos: 58,
    endPos: 58,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: " ",
  },
  {
    field: "conta",
    startPos: 59,
    endPos: 70,
    length: 12,
    required: true,
    type: "numeric",
  },
  {
    field: "dv_conta",
    startPos: 71,
    endPos: 71,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: " ",
  },
  {
    field: "dac",
    startPos: 72,
    endPos: 72,
    length: 1,
    required: false,
    default: " ",
  },
  {
    field: "empresa_nome",
    startPos: 73,
    endPos: 102,
    length: 30,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "nome_banco",
    startPos: 103,
    endPos: 132,
    length: 30,
    required: true,
    type: "alphanumeric",
    default: "ITAU",
  },
  {
    field: "brancos",
    startPos: 133,
    endPos: 142,
    length: 10,
    required: false,
    default: new Array(10).fill(" ").join(""),
  },
  {
    field: "arquivo_cod",
    startPos: 143,
    endPos: 143,
    length: 1,
    required: true,
    default: 1,
  },
  {
    field: "arquivo_data_geracao",
    startPos: 144,
    endPos: 151,
    length: 8,
    required: true,
    type: "date",
  },
  {
    field: "arquivo_hora_geracao",
    startPos: 152,
    endPos: 157,
    length: 6,
    required: true,
    type: "time",
  },
  {
    field: "lote",
    startPos: 158,
    endPos: 163,
    length: 6,
    required: true,
    type: "numeric",
    default: "0001",
  },
  {
    field: "layout_arquivo",
    startPos: 164,
    endPos: 166,
    length: 3,
    required: false,
    default: "089",
    type: "alphanumeric",
  },
  {
    field: "densidade",
    startPos: 167,
    endPos: 171,
    length: 5,
    required: false,
    default: "01600",
  },
  {
    field: "pix",
    startPos: 172,
    endPos: 174,
    length: 3,
    required: false,
    default: new Array(3).fill(" ").join(""), // ^ Aparentemente esse que é o padrão
  },
  {
    field: "uso_empresa",
    startPos: 174,
    endPos: 291,
    length: 17,
    required: false,
    default: new Array(17).fill(" ").join(""), // ^ Aparentemente esse que é o padrão
  },
  {
    field: "uso_empresa",
    startPos: 192,
    endPos: 211,
    length: 20,
    required: false,
    default: new Array(20).fill(" ").join(""), // ^ Aparentemente esse que é o padrão
  },
  {
    field: "brancos",
    startPos: 212,
    endPos: 240,
    length: 29,
    required: false,
    type: "alphanumeric",
    default: new Array(29).fill(" ").join(""),
  },
];
