// OK
module.exports = [
  {
    field: "tipo_registro",
    startPos: 1,
    endPos: 1,
    length: 1,
    required: true,
    type: "numeric",
    default: 1,
  },
  {
    field: "cod_inscricao",
    startPos: 2,
    endPos: 3,
    length: 2,
    required: true,
    type: "numeric",
    default: "02",
  },
  {
    field: "num_inscricao", //* CNPJ
    startPos: 4,
    endPos: 17,
    length: 14,
    required: true,
    type: "numeric",
  },
  {
    field: "zeros",
    startPos: 18,
    endPos: 20,
    length: 3,
    type: "alphanumeric",
    default: new Array(3).fill(0).join(""),
  },
  {
    field: "zeros",
    startPos: 21,
    endPos: 21,
    length: 1,
    type: "alphanumeric",
    default: new Array(1).fill(0).join(""),
  },
  {
    field: "num_carteira",
    startPos: 22,
    endPos: 24,
    length: 3,
    required: true,
    type: "numeric",
    default: 109, //* No exemplo é 109
  },
  {
    field: "agencia",
    startPos: 25,
    endPos: 29,
    length: 4,
    required: true,
    type: "numeric",
  },
  {
    field: "conta",
    startPos: 20,
    endPos: 36,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "dv_conta",
    startPos: 37,
    endPos: 37,
    length: 5,
    required: false,
    type: "alphanumeric",
    default: new Array(1).fill(0).join(""),
  },
  {
    field: "uso_empresa", //* ID Boleto
    startPos: 38,
    endPos: 62,
    length: 25,
    required: false,
    type: "alphanumeric",
    default: new Array(25).fill(" ").join(""),
  },
  {
    field: "brancos",
    startPos: 63,
    endPos: 70,
    length: 8,
    type: "alphanumeric",
    default: new Array(8).fill(" ").join(""),
  },
  {
    field: "nosso_numero_confirmado",
    startPos: 71,
    endPos: 82,
    length: 12,
    required: false,
    type: "alphanumeric",
    default: new Array(12).fill(0).join(""),
  },
  {
    field: "brancos",
    startPos: 83,
    endPos: 104,
    length: 22,
    required: false,
    type: "alphanumeric",
    default: new Array(22).fill(" ").join(""),
  },
  {
    field: "rateio_credito",
    startPos: 105,
    endPos: 105,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: new Array(1).fill(" ").join(""),
  },
  {
    field: "pagamento_parcial",
    startPos: 106,
    endPos: 107,
    length: 2,
    required: false,
    type: "alphanumeric",
    default: new Array(2).fill(" ").join(""),
  },
  {
    field: "carteira",
    startPos: 108,
    endPos: 108,
    length: 1,
    required: true,
    type: "alphanumeric",
    default: new Array(1).fill(0).join(""),
  },
  {
    field: "cod_ocorrencia",
    startPos: 109,
    endPos: 110,
    length: 2,
    type: "numeric",
    required: true,
    default: "01",
  },
  {
    field: "data_ocorrencia",
    startPos: 111,
    endPos: 116,
    length: 6,
    required: true,
    type: "date",
    default: new Array(6).fill(0).join(""),
  },
  {
    field: "num_doc",
    startPos: 117,
    endPos: 126,
    length: 10,
    required: true,
    type: "alphanumeric",
    default: new Array(10).fill(0).join(""),
  },
  {
    field: "nosso_numero_2",
    startPos: 127,
    endPos: 146,
    length: 20,
    required: false,
    type: "alphanumeric",
    default: new Array(20).fill(0).join(""),
  },
  {
    field: "data_vencimento",
    startPos: 147,
    endPos: 152,
    length: 6,
    required: true,
    type: "date",
    default: new Array(6).fill(0).join(""),
  },
  {
    field: "valor_titulo",
    startPos: 153,
    endPos: 165,
    length: 13,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "banco",
    startPos: 166,
    endPos: 168,
    length: 3,
    required: true,
    type: "numeric",
    default: 341,
  },
  {
    field: "agencia",
    startPos: 169,
    endPos: 173,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "especie",
    startPos: 174,
    endPos: 175,
    length: 2,
    required: true,
    type: "alphanumeric",
    default: "01",
  },
  {
    field: "tarifa_cobranca",
    startPos: 176,
    endPos: 188,
    length: 13,
    required: true,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "outras_tarifas",
    startPos: 189,
    endPos: 201,
    length: 13,
    required: true,
    type: "alphanumeric",
    default: new Array(13).fill(" ").join(""),
  },
  {
    field: "juros_atraso",
    startPos: 202,
    endPos: 214,
    length: 13,
    required: true,
    type: "numeric",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "valor_iof",
    startPos: 215,
    endPos: 227,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "valor_abatimento",
    startPos: 228,
    endPos: 240,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "descontos",
    startPos: 241,
    endPos: 253,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "valor_principal",
    startPos: 254,
    endPos: 266,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "juros_mora",
    startPos: 267,
    endPos: 279,
    length: 13,
    required: true,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "outros_creditos",
    startPos: 280,
    endPos: 292,
    length: 13,
    required: true,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "bracos",
    startPos: 293,
    endPos: 294,
    length: 2,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "motivo_ocorrencia",
    startPos: 295,
    endPos: 295,
    length: 2,
    required: true,
    type: "alphanumeric",
    default: new Array(2).fill(" ").join(""),
  },
  {
    field: "data_credito",
    startPos: 296,
    endPos: 301,
    length: 6,
    required: true,
    type: "date",
    default: new Array(6).fill(0).join(""),
  },
  {
    field: "origem_pagamento",
    startPos: 302,
    endPos: 304,
    length: 3,
    required: true,
    type: "numeric",
    default: new Array(3).fill(0).join(""),
  },
  {
    field: "brancos",
    startPos: 305,
    endPos: 314,
    length: 10,
    required: true,
    type: "alphanumeric",
    default: new Array(10).fill(" ").join(""),
  },
  {
    field: "cod_banco",
    startPos: 315,
    endPos: 318,
    length: 4,
    required: true,
    type: "alphanumeric",
    default: new Array(4).fill(0).join(""),
  },
  {
    field: "motivo_rejeicao",
    startPos: 319,
    endPos: 328,
    length: 10,
    required: true,
    type: "alphanumeric",
    default: new Array(10).fill(" ").join(""),
  },
  {
    field: "brancos",
    startPos: 329,
    endPos: 368,
    length: 40,
    required: false,
    type: "alphanumeric",
    default: new Array(40).fill(" ").join(""),
  },
  {
    field: "num_cartorio",
    startPos: 369,
    endPos: 370,
    length: 2,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "num_protocolo",
    startPos: 371,
    endPos: 380,
    length: 10,
    required: false,
    type: "alphanumeric",
    default: new Array(10).fill(" ").join(""),
  },
  {
    field: "brancos",
    startPos: 381,
    endPos: 394,
    length: 14,
    required: false,
    type: "alphanumeric",
    default: new Array(14).fill(" ").join(""),
  },
  {
    field: "num_sequencial",
    startPos: 395,
    endPos: 400,
    length: 6,
    required: true,
    type: "numeric",
  },
];
