module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    required: true,
    default: 341,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    required: true,
    type: "numeric",
    default: "0001",
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    required: true,
    default: 1,
  },
  {
    field: "operacao",
    startPos: 9,
    endPos: 9,
    length: 1,
    required: true,
    default: "C",
    type: "alphanumeric",
  },
  {
    field: "tipo_pagamento",
    startPos: 10,
    endPos: 11,
    length: 2,
    required: true,
    type: "numeric",
    default: "20", //? Realmente é fornecedores?
  },
  {
    field: "forma_pagamento",
    startPos: 12,
    endPos: 13,
    length: 2,
    required: true,
    type: "numeric",
    default: "06",
  },
  {
    field: "versao_layout",
    startPos: 14,
    endPos: 16,
    length: 3,
    required: true,
    default: "040",
  },
  {
    field: "brancos",
    startPos: 17,
    endPos: 17,
    length: 1,
    required: false,
    default: " ",
  },
  {
    field: "empresa_tipo_insc",
    startPos: 18,
    endPos: 18,
    length: 1,
    required: true,
    type: "numeric",
    default: "2",
  },
  {
    field: "cnpj_empresa",
    startPos: 19,
    endPos: 32,
    length: 14,
    required: true,
    type: "numeric",
  },
  {
    field: "identificacao_lancamento",
    startPos: 33,
    endPos: 36,
    length: 4,
    required: true,
    type: "numeric",
    default: new Array(4).fill(" ").join(""), //^ Rever o manual caso necessário
  },
  {
    field: "brancos",
    startPos: 37,
    endPos: 52,
    length: 16,
    required: false,
    default: new Array(16).fill(" ").join(""),
  },
  {
    field: "agencia",
    startPos: 53,
    endPos: 57,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "brancos",
    startPos: 58,
    endPos: 58,
    length: 1,
    required: false,
    default: " ",
  },
  {
    field: "conta",
    startPos: 59,
    endPos: 70,
    length: 12,
    required: true,
    type: "numeric",
  },
  {
    field: "branco",
    startPos: 71,
    endPos: 71,
    length: 1,
    required: false,
    type: "numeric",
    default: " ",
  },
  {
    field: "dv_conta",
    startPos: 72,
    endPos: 72,
    length: 1,
    required: false,
    default: " ",
  },
  {
    field: "empresa_nome",
    startPos: 73,
    endPos: 102,
    length: 30,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "finalidade",
    startPos: 103,
    endPos: 132,
    length: 30,
    required: false,
    type: "alphanumeric",
    default: new Array(30).fill(" ").join(""), //^ Rever o manual caso necessário
  },
  {
    field: "historico_cc",
    startPos: 103,
    endPos: 132,
    length: 10,
    required: false,
    type: "alphanumeric",
    default: new Array(10).fill(" ").join(""),
  },

  {
    field: "endereco_empresa",
    startPos: 143,
    endPos: 172,
    length: 30,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "endereco_num",
    startPos: 173,
    endPos: 177,
    length: 5,
    required: false,
    type: "alphanumeric", //^ Em alguns o numero é SN
  },
  {
    field: "endereco_compl",
    startPos: 178,
    endPos: 192,
    length: 15,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "cidade",
    startPos: 193,
    endPos: 212,
    length: 20,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "cep",
    startPos: 213,
    endPos: 220,
    length: 8,
    required: false,
    type: "numeric",
  },
  {
    field: "uf",
    startPos: 221,
    endPos: 222,
    length: 2,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "brancos",
    startPos: 223,
    endPos: 230,
    length: 8,
    required: false,
    default: new Array(8).fill(" ").join(""),
  },
  {
    field: "codigos_ocorrencias",
    startPos: 231,
    endPos: 240,
    length: 10,
    required: false,
    default: new Array(10).fill(" ").join(""),
  },
];
