module.exports = {
  ArquivoHeader: {
    REGISTRY_FIELD: "registro",
    ARQUIVO_COD: {
      REMESSA: "1",
      RETORNO: "2",
    },
    TIPO_INSC_EMPRESA: {
      ISENTO: "0",
      CPF: "1",
      CNPJ: "2",
      PIS_PASEP: "3",
      OUTRO: "9",
    },
  },
  ArquivoTrailer: {
    TOTAL_LOTES_FIELD: "qtde_lotes",
    REGISTRY_FIELD: "registro",
  },
  Pagamento: {
    REGISTRY_FIELD: "cod_seg_registro_lote",
    TIPO_MOVIMENTO: {
      // tipo de movimento a que o detalhe se destina
      INCLUSAO: 0,
      CONSULTA: 1,
      ESTORNO: 3,
      ALTERACAO: 5,
      LIQUIDACAO: 7,
      EXCLUSAO: 9,
    },
    CODIGO_MOVIMENTO: {
      // indica a movimentação a ser efetuada
      INCLUSAO: "00", // inclusão com registro detalhe
      INCLUSAO_COM_BLOQUEIO: "09",
    }, // inclusão com bloqueio
    COD_CAMARA_CENTRALIZADORA: {
      TED: "18",
      DOC: "700",
    },
  },
  Detail: "A",
  Segmentos: {
    A: "Detail",
    B: "Detail2",
    C: false,
    5: false,
  },
  CodigosOcorrencias: {
    2: "ENTRADA CONFIRMADA COM POSSIBILIDADE DE MENSAGEM (NOTA 20 – TABELA 10)",
    3: "ENTRADA REJEITADA (NOTA 20 – TABELA 1)",
    4: "ALTERAÇÃO DE DADOS – NOVA ENTRADA OU ALTERAÇÃO/EXCLUSÃO DE DADOS ACATADA",
    5: "ALTERAÇÃO DE DADOS – BAIXA",
    6: "LIQUIDAÇÃO NORMAL",
    7: "LIQUIDAÇÃO PARCIAL – COBRANÇA INTELIGENTE (B2B)",
    8: "LIQUIDAÇÃO EM CARTÓRIO",
    9: "BAIXA SIMPLES",
    10: "BAIXA POR TER SIDO LIQUIDADO",
    11: "EM SER (SÓ NO RETORNO MENSAL)",
    12: "ABATIMENTO CONCEDIDO",
    13: "ABATIMENTO CANCELADO",
    14: "VENCIMENTO ALTERADO",
    15: "BAIXAS REJEITADAS (NOTA 20 – TABELA 4)",
    16: "INSTRUÇÕES REJEITADAS (NOTA 20 – TABELA 3)",
    17: "ALTERAÇÃO/EXCLUSÃO DE DADOS REJEITADOS (NOTA 20 – TABELA 2)",
    18: "COBRANÇA CONTRATUAL – INSTRUÇÕES/ALTERAÇÕES REJEITADAS/PENDENTES (NOTA 20 – TABELA 5)",
    19: "CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE PROTESTO",
    20: "CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE SUSTAÇÃO DE PROTESTO /TARIFA",
    21: "CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE NÃO PROTESTAR",
    23: "TÍTULO ENVIADO A CARTÓRIO/TARIFA",
    24: "INSTRUÇÃO DE PROTESTO REJEITADA / SUSTADA / PENDENTE (NOTA 20 – TABELA 7)",
    25: "ALEGAÇÕES DO PAGADOR (NOTA 20 – TABELA 6)",
    26: "TARIFA DE AVISO DE COBRANÇA",
    27: "TARIFA DE EXTRATO POSIÇÃO (B40X)",
    28: "TARIFA DE RELAÇÃO DAS LIQUIDAÇÕES",
    29: "TARIFA DE MANUTENÇÃO DE TÍTULOS VENCIDOS",
    30: "DÉBITO MENSAL DE TARIFAS (PARA ENTRADAS E BAIXAS)",
    32: "BAIXA POR TER SIDO PROTESTADO",
    33: "CUSTAS DE PROTESTO",
    34: "CUSTAS DE SUSTAÇÃO",
    35: "CUSTAS DE CARTÓRIO DISTRIBUIDOR",
    36: "CUSTAS DE EDITAL",
    37: "TARIFA DE EMISSÃO DE BOLETO/TARIFA DE ENVIO DE DUPLICATA",
    38: "TARIFA DE INSTRUÇÃO",
    39: "TARIFA DE OCORRÊNCIAS",
    40: "TARIFA MENSAL DE EMISSÃO DE BOLETO/TARIFA MENSAL DE ENVIO DE DUPLICATA",
    41: "DÉBITO MENSAL DE TARIFAS – EXTRATO DE POSIÇÃO (B4EP/B4OX)",
    42: "DÉBITO MENSAL DE TARIFAS – OUTRAS INSTRUÇÕES",
    43: "DÉBITO MENSAL DE TARIFAS – MANUTENÇÃO DE TÍTULOS VENCIDOS",
    44: "DÉBITO MENSAL DE TARIFAS – OUTRAS OCORRÊNCIAS",
    45: "DÉBITO MENSAL DE TARIFAS – PROTESTO",
    46: "DÉBITO MENSAL DE TARIFAS – SUSTAÇÃO DE PROTESTO",
    47: "BAIXA COM TRANSFERÊNCIA PARA DESCONTO",
    48: "CUSTAS DE SUSTAÇÃO JUDICIAL",
    51: "TARIFA MENSAL REF A ENTRADAS BANCOS CORRESPONDENTES NA CARTEIRA",
    52: "TARIFA MENSAL BAIXAS NA CARTEIRA",
    53: "TARIFA MENSAL BAIXAS EM BANCOS CORRESPONDENTES NA CARTEIRA",
    54: "TARIFA MENSAL DE LIQUIDAÇÕES NA CARTEIRA",
    55: "TARIFA MENSAL DE LIQUIDAÇÕES EM BANCOS CORRESPONDENTES NA CARTEIRA",
    56: "CUSTAS DE IRREGULARIDADE",
    57: "INSTRUÇÃO CANCELADA (NOTA 20 – TABELA 8)",
    59: "BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG",
    60: "ENTRADA REJEITADA CARNÊ (NOTA 20 – TABELA 1)",
    61: "TARIFA EMISSÃO AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)",
    62: "DÉBITO MENSAL DE TARIFA – AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)",
    63: "TÍTULO SUSTADO JUDICIALMENTE",
    64: "ENTRADA CONFIRMADA COM RATEIO DE CRÉDITO",
    65: "PAGAMENTO COM CHEQUE – AGUARDANDO COMPENSAÇÃO",
    69: "CHEQUE DEVOLVIDO (NOTA 20 – TABELA 9)",
    71: "ENTRADA REGISTRADA, AGUARDANDO AVALIAÇÃO",
    72: "BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG SEM TÍTULO CORRESPONDENTE",
    73: "CONFIRMAÇÃO DE ENTRADA NA COBRANÇA SIMPLES – ENTRADA NÃO ACEITA NA COBRANÇA CONTRATUAL",
    74: "INSTRUÇÃO DE NEGATIVAÇÃO EXPRESSA REJEITADA (NOTA 20 – TABELA 11)",
    75: "CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA",
    76: "CHEQUE COMPENSADO",
    77: "CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE EXCLUSÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA",
    78: "CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA",
    79: "NEGATIVAÇÃO EXPRESSA INFORMACIONAL (NOTA 20 – TABELA 12)",
    80: "CONFIRMAÇÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA – TARIFA",
    82: "CONFIRMAÇÃO DO CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA – TARIFA",
    83: "CONFIRMAÇÃO DE EXCLUSÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA POR LIQUIDAÇÃO – TARIFA",
    85: "TARIFA POR BOLETO (ATÉ 03 ENVIOS) COBRANÇA ATIVA ELETRÔNICA",
    86: "TARIFA EMAIL COBRANÇA ATIVA ELETRÔNICA",
    87: "TARIFA SMS COBRANÇA ATIVA ELETRÔNICA",
    88: "TARIFA MENSAL POR BOLETO (ATÉ 03 ENVIOS) COBRANÇA ATIVA ELETRÔNICA",
    89: "TARIFA MENSAL EMAIL COBRANÇA ATIVA ELETRÔNICA JANEIRO 2017 Cobrança CNAB 400 25",
    90: "TARIFA MENSAL SMS COBRANÇA ATIVA ELETRÔNICA",
    91: "TARIFA MENSAL DE EXCLUSÃO DE ENTRADA DE NEGATIVAÇÃO EXPRESSA",
    92: "TARIFA MENSAL DE CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA",
    93: "TARIFA MENSAL DE EXCLUSÃO DE NEGATIVAÇÃO EXPRESSA POR LIQUIDAÇÃO",
  },
  FinalidadeTED: {
    "00001": "Pagamento de Imposto, Tributos e Taxas",
    "00002": "Pagamentos a concessionárias de serviços Públicos",
    "00003": "Pagamentos de Dividendos",
    "00004": "Pagamentos de Salários",
    "00005": "Pagamentos de Fornecedores",
    "00006": "Pagamentos de Honorários",
    "00007": "Pagamentos de Aluguéis e Taxas e Condomínio",
    "00008": "Pagamentos de Duplicatas e Títulos",
    "00009": "Pagamentos de Honorários",
    "00010": "Créditos em Conta",
    "00011": "Pagamentos a Corretoras",
    "00016": "Créditos em Conta Investimento",
    "00100": "Depósitos Judiciais",
    "00101": "Pensões Alimentícias",
    "00200": "Transferências Internacional de Reais",
    "00201": "Ajustes Posição Mercado Futuro",
    "00202": "Repasse de Valores do BNDS",
    "00203": "Liquidação de Compromisso com BNDS",
    "00204": "Compra/Venda de Ações – Bolsa de Valores e Mercado de Balcão",
    "00205": "Contrato referenciado em Ações/Índices de Ações – BV/BMF",
    "00300": "Restituição Imposto de Renda",
    "00500": "Restituição Prêmio de Seguros",
    "00501": "Pagamento de Indenização de Sinistro de Seguro",
    "00502": "Pagamento de Prêmio de Co-seguro",
    "00503": "Restituição de Prêmio de CO-Seguro",
    "00504": "Pagamentos de Indenização de CO-Seguro",
    "00505": "Pagamentos de Prêmio de Resseguro",
    "00506": "Restituição de Prêmio de Resseguro",
    "00507": "Pagamento de Indenização de sinistro de Resseguro",
    "00508": "Restituição de Indenização de Sinistro de Resseguro",
    "00509": "Pagamento de Despesas com sinistros",
    "00510": "Pagamento de Inspeções/Vistorias Prévias",
    "00511": "Pagamento de Resgate de Título de Capitalização",
    "00512": "Pagamento de Sorteio de Título de Capitalização",
    "00513": "Pagamento de Devolução de Mensalidade de Títulos de Capitalização",
    "00514": "Restituição de Contribuição de Plano Previdência",
    "00515": "Pagamento de Beneficio Previdência de Pecúlio",
    "00516": "Pagamento de Beneficio Previdenciário de Pensão",
    "00517": "Pagamento de Beneficio Previdenciário de Aposentadoria",
    "00518": "Pagamento de Resgate Previdenciário",
    "00519": "Pagamento de Comissão de Corretagem",
    "00520": "Pagamento de Transferências/Portabilidade de Reserva de Seguro/Previdência",
    "99999": "Outros",
  },
};
