module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    required: true,
    default: 341,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    type: "numeric",
    required: true,
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    required: true,
    default: 3,
  },
  {
    field: "num_registro_lote",
    startPos: 9,
    endPos: 13,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "cod_seg_registro_lote",
    startPos: 14,
    endPos: 14,
    length: 1,
    required: true,
    default: "J",
    type: "alphanumeric",
  },
  {
    field: "movimento_tipo",
    startPos: 15,
    endPos: 17,
    length: 3,
    required: true,
    type: "numeric",
    default: 0,
  },
  {
    field: "codigo_registro",
    startPos: 18,
    endPos: 19,
    length: 2,
    required: true,
    type: "numeric",
    default: 52,
  },
  {
    field: "inscricao_sacado",
    startPos: 20,
    endPos: 20,
    length: 1,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "num_inscricao_sacado",
    startPos: 21,
    endPos: 35,
    length: 15,
    type: "numeric",
    required: true,
  },
  {
    field: "nome_sacado",
    startPos: 36,
    endPos: 75,
    length: 40,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "inscricao_cedente",
    startPos: 76,
    endPos: 76,
    length: 1,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "num_inscricao_cedente",
    startPos: 77,
    endPos: 91,
    length: 15,
    required: true,
    type: "numeric",
  },
  {
    field: "nome_cedente",
    startPos: 92,
    endPos: 131,
    length: 40,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "chave_pagamento",
    startPos: 132,
    endPos: 208,
    length: 77,
    required: true,
    type: "alphanumeric",
    format: "any",
  },
  {
    field: "txid",
    startPos: 209,
    endPos: 340,
    length: 32,
    required: false,
    type: "alphanumeric",
    default: new Array(32).fill(" ").join(""),
  },
];
