// OK
module.exports = [
  {
    field: "tipo_registro",
    startPos: 1,
    endPos: 1,
    length: 1,
    required: true,
    type: "numeric",
    default: 1,
  },
  {
    field: "cod_inscricao",
    startPos: 2,
    endPos: 3,
    length: 2,
    required: true,
    type: "numeric",
    default: "02",
  },
  {
    field: "num_inscricao", //* CNPJ
    startPos: 4,
    endPos: 17,
    length: 14,
    required: true,
    type: "numeric",
  },
  {
    field: "agencia",
    startPos: 18,
    endPos: 21,
    length: 4,
    required: true,
    type: "numeric",
  },
  {
    field: "zeros",
    startPos: 22,
    endPos: 23,
    length: 2,
    type: "alphanumeric",
    default: new Array(2).fill(0).join(""),
  },
  {
    field: "conta",
    startPos: 24,
    endPos: 28,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "dac",
    startPos: 29,
    endPos: 29,
    length: 1,
    required: false,
    type: "numeric",
    default: 0,
  },
  {
    field: "brancos",
    startPos: 30,
    endPos: 33,
    length: 4,
    type: "alphanumeric",
    default: new Array(4).fill(" ").join(""),
  },
  {
    field: "instrucao",
    startPos: 34,
    endPos: 37,
    length: 4,
    required: false,
    type: "numeric",
    default: new Array(4).fill(0).join(""),
  },
  {
    field: "uso_empresa", //* ID Boleto
    startPos: 38,
    endPos: 62,
    length: 25,
    required: false,
    type: "alphanumeric",
    default: new Array(25).fill(" ").join(""),
  },
  {
    field: "nosso_numero", //* ID Boleto (REPETE)
    startPos: 63,
    endPos: 70,
    length: 8,
    required: true,
    type: "numeric",
  },
  {
    field: "qtde_moeda",
    startPos: 71,
    endPos: 83,
    length: 13,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "num_carteira",
    startPos: 84,
    endPos: 86,
    length: 3,
    required: true,
    type: "numeric",
    default: 109, //* No exemplo é 109
  },
  {
    field: "uso_banco",
    startPos: 87,
    endPos: 107,
    length: 21,
    required: false,
    type: "alphanumeric",
    default: new Array(3).fill(0).join(""),
  },
  {
    field: "cod_carteira",
    startPos: 108,
    endPos: 108,
    length: 1,
    required: true,
    type: "alphanumeric",
    default: "I", //* No exemplo é I
  },
  {
    field: "cod_ocorrencia",
    startPos: 109,
    endPos: 110,
    length: 2,
    type: "numeric",
    required: true,
    default: "01", //* No exemplo é 01
  },
  {
    field: "num_doc",
    startPos: 111,
    endPos: 120,
    length: 10,
    required: true,
    type: "alphanumeric",
    default: new Array(20).fill(0).join(""),
  }, //* Necessário cálculo
  {
    field: "data_vencimento",
    startPos: 121,
    endPos: 126,
    length: 6,
    required: true,
    type: "date",
  }, //* Geralmente dois dias após a data de geração
  {
    field: "valor_titulo",
    startPos: 127,
    endPos: 139,
    length: 13,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "banco",
    startPos: 140,
    endPos: 142,
    length: 3,
    required: true,
    type: "numeric",
    default: 341,
  },
  {
    field: "agencia",
    startPos: 143,
    endPos: 147,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "especie",
    startPos: 148,
    endPos: 149,
    length: 2,
    required: true,
    type: "alphanumeric",
    default: "01", //* No exemplo é 01
  },
  {
    field: "aceite",
    startPos: 150,
    endPos: 150,
    length: 1,
    required: true,
    type: "alphanumeric",
    default: "N", //* No exemplo é N
  },
  {
    field: "data_emissao",
    startPos: 151,
    endPos: 156,
    length: 6,
    required: true,
    type: "date",
  },
  {
    field: "instrucao_1",
    startPos: 157,
    endPos: 158,
    length: 2,
    required: true,
    type: "alphanumeric",
    default: "05", //* No exemplo é 05
  },
  {
    field: "instrucao_2",
    startPos: 159,
    endPos: 160,
    length: 2,
    required: true,
    type: "alphanumeric",
    default: "00", //* No exemplo é 00
  },
  {
    field: "juros_mora",
    startPos: 161,
    endPos: 173,
    length: 13,
    required: true,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "data_desconto",
    startPos: 174,
    endPos: 179,
    length: 6,
    required: false,
    type: "date",
    default: new Array(6).fill(0).join(""),
  },
  {
    field: "valor_desconto",
    startPos: 180,
    endPos: 192,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "valor_iof",
    startPos: 193,
    endPos: 205,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "abatimento",
    startPos: 206,
    endPos: 218,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "cod_inscricao_pagador",
    startPos: 219,
    endPos: 220,
    length: 2,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "num_inscricao_pagador",
    startPos: 221,
    endPos: 234,
    length: 14,
    required: true,
    type: "numeric",
  },
  {
    field: "nome_pagador",
    startPos: 235,
    endPos: 264,
    length: 30,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "brancos",
    startPos: 265,
    endPos: 274,
    length: 10,
    required: true,
    type: "alphanumeric",
    default: new Array(10).fill(" ").join(""),
  },
  {
    field: "logradouro",
    startPos: 275,
    endPos: 314,
    length: 40,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "municipio",
    startPos: 315,
    endPos: 326,
    length: 12,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "cep",
    startPos: 327,
    endPos: 334,
    length: 8,
    required: false,
    type: "numeric",
  },
  {
    field: "cidade",
    startPos: 335,
    endPos: 349,
    length: 15,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "uf",
    startPos: 350,
    endPos: 351,
    length: 2,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "nome_sacador",
    startPos: 352,
    endPos: 381,
    length: 30,
    required: false,
    type: "alphanumeric",
    default: new Array(30).fill(" ").join(""),
  },
  {
    field: "brancos",
    startPos: 382,
    endPos: 385,
    length: 4,
    required: false,
    type: "alphanumeric",
    default: new Array(4).fill(" ").join(""),
  },
  {
    field: "data_mora",
    startPos: 386,
    endPos: 391,
    length: 6,
    required: false,
    type: "date",
    default: new Array(6).fill(0).join(""),
  },
  {
    field: "prazo",
    startPos: 392,
    endPos: 393,
    length: 2,
    type: "numeric",
    default: "05",
  },
  {
    field: "brancos",
    startPos: 394,
    endPos: 394,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: " ",
  },
  {
    field: "num_sequencial",
    startPos: 395,
    endPos: 400,
    length: 6,
    required: true,
    type: "numeric",
  },
];
