// OK
module.exports = [
  {
    field: "tipo_registro",
    startPos: 1,
    endPos: 1,
    length: 1,
    required: true,
    type: "numeric",
    default: 1,
  },
  {
    field: "agencia_debito",
    startPos: 2,
    endPos: 6,
    length: 5,
    required: false,
    type: "numeric",
    default: new Array(5).fill(0).join(""),
  },
  {
    field: "dv_agencia_debito",
    startPos: 7,
    endPos: 7,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: new Array(1).fill(" ").join(""),
  },
  {
    field: "razao_conta_corrente",
    startPos: 8,
    endPos: 12,
    length: 5,
    required: false,
    type: "numeric",
    default: new Array(5).fill(0).join(""),
  },
  {
    field: "conta_debito",
    startPos: 13,
    endPos: 19,
    length: 7,
    required: false,
    type: "numeric",
    default: new Array(7).fill(0).join(""),
  },
  {
    field: "dv_conta_debito",
    startPos: 20,
    endPos: 20,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: new Array(1).fill(" ").join(""),
  },
  {
    field: "zeros",
    startPos: 21,
    endPos: 21,
    length: 1,
    type: "alphanumeric",
    default: new Array(1).fill(0).join(""),
  },
  {
    field: "num_carteira",
    startPos: 22,
    endPos: 24,
    length: 3,
    required: true,
    type: "numeric",
    default: 109, //* No exemplo é 109
  },
  {
    field: "agencia",
    startPos: 25,
    endPos: 29,
    length: 4,
    required: true,
    type: "numeric",
  },
  {
    field: "conta",
    startPos: 20,
    endPos: 36,
    length: 5,
    required: true,
    type: "numeric",
  },
  {
    field: "dv_conta",
    startPos: 37,
    endPos: 37,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: new Array(1).fill(" ").join(""),
  },
  {
    field: "uso_empresa", //* ID Boleto
    startPos: 38,
    endPos: 62,
    length: 25,
    required: false,
    type: "alphanumeric",
    default: new Array(25).fill(" ").join(""),
  },
  {
    field: "banco_debitado",
    startPos: 63,
    endPos: 65,
    length: 3,
    type: "alphanumeric",
    default: new Array(3).fill(" ").join(""),
  },
  {
    field: "campo_multa",
    startPos: 66,
    endPos: 66,
    length: 1,
    required: true,
    type: "numeric",
    default: 0,
  },
  {
    field: "percentual_multa",
    startPos: 67,
    endPos: 70,
    length: 4,
    required: false,
    type: "numeric",
    default: new Array(4).fill(0).join(""),
  },
  {
    field: "nosso_numero",
    startPos: 71,
    endPos: 81,
    length: 11,
    required: false,
    type: "numeric",
    default: new Array(11).fill(0).join(""),
  },
  {
    field: "dac",
    startPos: 82,
    endPos: 82,
    length: 1,
    required: false,
    type: "numeric",
    default: 0,
  },
  {
    field: "desconto_bonificacao",
    startPos: 83,
    endPos: 92,
    length: 10,
    type: "numeric",
    format: "float",
    default: new Array(10).fill(0).join(""),
  },
  {
    field: "condicao_emissao_cobranca",
    startPos: 93,
    endPos: 93,
    length: 1,
    required: false,
    type: "numeric",
    default: 1,
  },
  {
    field: "emite_boleto_debito",
    startPos: 94,
    endPos: 94,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: "N",
  },
  {
    field: "operacao_banco",
    startPos: 95,
    endPos: 104,
    length: 10,
    required: false,
    type: "alphanumeric",
    default: new Array(10).fill(" ").join(""),
  },
  {
    field: "rateio_credito",
    startPos: 105,
    endPos: 105,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: new Array(1).fill(" ").join(""),
  },
  {
    field: "endereco_aviso",
    startPos: 106,
    endPos: 106,
    length: 1,
    required: false,
    type: "numeric",
    default: 2,
  },
  {
    field: "pagamento_parcial",
    startPos: 107,
    endPos: 108,
    length: 2,
    required: false,
    type: "alphanumeric",
    default: new Array(2).fill(" ").join(""),
  },
  {
    field: "cod_ocorrencia",
    startPos: 109,
    endPos: 110,
    length: 2,
    type: "numeric",
    required: true,
    default: "01", //* No exemplo é 01
  },
  {
    field: "num_doc",
    startPos: 111,
    endPos: 120,
    length: 10,
    required: true,
    type: "alphanumeric",
    default: new Array(10).fill(0).join(""),
  }, //* Necessário cálculo
  {
    field: "data_vencimento",
    startPos: 121,
    endPos: 126,
    length: 6,
    required: true,
    type: "date",
  }, //* Geralmente dois dias após a data de geração
  {
    field: "valor_titulo",
    startPos: 127,
    endPos: 139,
    length: 13,
    required: true,
    type: "numeric",
    format: "float",
  },
  {
    field: "banco",
    startPos: 140,
    endPos: 142,
    length: 3,
    required: true,
    type: "numeric",
    default: new Array(3).fill(0).join(""),
  },
  {
    field: "agencia",
    startPos: 143,
    endPos: 147,
    length: 5,
    required: true,
    type: "numeric",
    default: new Array(5).fill(0).join(""),
  },
  {
    field: "especie",
    startPos: 148,
    endPos: 149,
    length: 2,
    required: true,
    type: "alphanumeric",
    default: "01", //* No exemplo é 01
  },
  {
    field: "aceite",
    startPos: 150,
    endPos: 150,
    length: 1,
    required: true,
    type: "alphanumeric",
    default: "N", //* No exemplo é N
  },
  {
    field: "data_emissao",
    startPos: 151,
    endPos: 156,
    length: 6,
    required: true,
    type: "date",
  },
  {
    field: "instrucao_1",
    startPos: 157,
    endPos: 158,
    length: 2,
    required: true,
    type: "alphanumeric",
    default: "05", //* No exemplo é 05
  },
  {
    field: "instrucao_2",
    startPos: 159,
    endPos: 160,
    length: 2,
    required: true,
    type: "alphanumeric",
    default: "00", //* No exemplo é 00
  },
  {
    field: "juros_mora",
    startPos: 161,
    endPos: 173,
    length: 13,
    required: true,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "data_desconto",
    startPos: 174,
    endPos: 179,
    length: 6,
    required: false,
    type: "date",
    default: new Array(6).fill(0).join(""),
  },
  {
    field: "valor_desconto",
    startPos: 180,
    endPos: 192,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "valor_iof",
    startPos: 193,
    endPos: 205,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "abatimento",
    startPos: 206,
    endPos: 218,
    length: 13,
    required: false,
    type: "numeric",
    format: "float",
    default: new Array(13).fill(0).join(""),
  },
  {
    field: "cod_inscricao_pagador",
    startPos: 219,
    endPos: 220,
    length: 2,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "num_inscricao_pagador",
    startPos: 221,
    endPos: 234,
    length: 14,
    required: true,
    type: "numeric",
  },
  {
    field: "nome_pagador",
    startPos: 235,
    endPos: 274,
    length: 40,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "logradouro",
    startPos: 275,
    endPos: 314,
    length: 40,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "mensagem_1",
    startPos: 315,
    endPos: 326,
    length: 12,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "cep",
    startPos: 327,
    endPos: 334,
    length: 8,
    required: false,
    type: "numeric",
  },
  {
    field: "mensagem_2",
    startPos: 335,
    endPos: 394,
    length: 60,
    required: true,
    type: "alphanumeric",
  },
  {
    field: "num_sequencial",
    startPos: 395,
    endPos: 400,
    length: 6,
    required: true,
    type: "numeric",
  },
];
