module.exports = [
  {
    field: "banco",
    startPos: 1,
    endPos: 3,
    length: 3,
    required: true,
    default: 341,
  },
  {
    field: "lote",
    startPos: 4,
    endPos: 7,
    length: 4,
    required: true,
    type: "numeric",
    default: "0000",
  },
  {
    field: "registro",
    startPos: 8,
    endPos: 8,
    length: 1,
    required: true,
    default: "0",
  },
  {
    field: "brancos",
    startPos: 9,
    endPos: 14,
    length: 6,
    required: false,
    default: new Array(6).fill(" ").join(""),
  },
  {
    field: "layout_arquivo",
    startPos: 15,
    endPos: 17,
    length: 3,
    required: false,
    default: "080", //^ No modelo é 081 mas no manual o exemplo 080 (VERIFICAR)
  },
  {
    field: "empresa_inscricao_tipo",
    startPos: 18,
    endPos: 18,
    length: 1,
    required: true,
    type: "numeric",
    default: 2,
  },
  {
    field: "cnpj_empresa",
    startPos: 19,
    endPos: 32,
    length: 14,
    required: true,
    type: "numeric",
  },
  {
    field: "brancos",
    startPos: 33,
    endPos: 52,
    length: 20,
    required: false,
    default: new Array(20).fill(" ").join(""),
  },
  {
    field: "agencia",
    startPos: 53,
    endPos: 57,
    length: 5,
    required: true,
    type: "numeric",
  }, //? É necessario add o dv_agencia?
  {
    field: "brancos",
    startPos: 58,
    endPos: 58,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: " ",
  },
  {
    field: "conta",
    startPos: 59,
    endPos: 70,
    length: 12,
    required: true,
    type: "numeric",
  },
  {
    field: "brancos",
    startPos: 71,
    endPos: 71,
    length: 1,
    required: false,
    type: "alphanumeric",
    default: " ",
  },
  {
    field: "dv_conta",
    startPos: 72,
    endPos: 72,
    length: 1,
    required: false,
    type: "numeric",
    default: "0",
  },
  {
    field: "empresa_nome",
    startPos: 73,
    endPos: 102,
    length: 30,
    required: false,
    type: "alphanumeric",
  },
  {
    field: "nome_banco",
    startPos: 103,
    endPos: 132,
    length: 30,
    required: true,
    type: "alphanumeric",
    default: "ITAU",
  },
  {
    field: "brancos",
    startPos: 133,
    endPos: 142,
    length: 10,
    required: false,
    default: new Array(10).fill(" ").join(""),
  },
  {
    field: "arquivo_cod",
    startPos: 143,
    endPos: 143,
    length: 1,
    required: true,
    default: 1,
  },
  {
    field: "arquivo_data_geracao",
    startPos: 144,
    endPos: 151,
    length: 8,
    required: true,
    type: "date",
  },
  {
    field: "arquivo_hora_geracao",
    startPos: 152,
    endPos: 157,
    length: 6,
    required: true,
    type: "hour",
  },

  {
    field: "zeros",
    startPos: 158,
    endPos: 166,
    length: 9,
    required: false,
    default: new Array(9).fill("0").join(""),
  },
  {
    field: "arquivo_densidade",
    startPos: 167,
    endPos: 171,
    length: 5,
    required: false,
    // default: "01600",
    default: new Array(5).fill("0").join(""), // ^ Aparentemente esse que é o padrão
  },
  {
    field: "brancos",
    startPos: 172,
    endPos: 240,
    length: 69,
    required: false,
    type: "alphanumeric",
    default: new Array(69).fill(" ").join(""),
  },
];
